base_folder: ~/msnovelist/
db_path: ''
db_path_train: '~/msnovelist/sirius6_db/1682855186/sirius6-b297c21c-cd1d-4d26-9c74-b62ed3399776.db'
fp_map: '~/MSNovelist-dev/data/fingerprint-map/csi_fingerid.csv'
hdf5_lock: "FALSE"
weights_folder: ~/MSNovelist-dev/data/weights/
eval_folder: ~/MSNovelist-dev/data/results/
log_folder: ~/MSNovelist-dev/data/tensorboard/
sirius_bin: /usr/local/bin/sirius/bin/sirius
fingerprinter_path: ~/MSNovelist-dev/fingerprint-wrapper/target/fingerprint-wrapper-bin-0.5.2.jar
fingerprinter_threads: 10
fingerprinter_cache: '~/MSNovelist-dev/data/fingerprint_cache.db'
training_verbose: 1
coverage_baseline: ''
batch_size: 256
rerank_sirius_results_n: 64
db_pubchem: ~/MSNovelist-dev/data/pubchem-dummy/pubchem_ref_dummy.db
db_path_eval:
    path: ~/MSNovelist-dev/data/minimal-dataset/minimal_dataset.csv
    fp_map: '~/MSNovelist-dev/data/fingerprint-map/csi_fingerid.csv'
    construct_from: 'smiles'
    reload_smiles_pubchem: True
    pipeline_options:
        fingerprint_selected: fingerprint_degraded
        embed_X: False
db_path_sample:
    path: ~/MSNovelist-dev/data/minimal-dataset/minimal_dataset.csv
    fp_map: '~/MSNovelist-dev/data/fingerprint-map/csi_fingerid.csv'
    construct_from: 'smiles'
    reload_smiles_pubchem: True
    pipeline_options:
        fingerprint_selected: fingerprint_degraded
        embed_X: False
eval_id: ''
eval_k: 128
eval_kk: 128
eval_n: 8
eval_steps: 128
eval_temperature: 1.0
