base_folder: /home/vo87poq/MSNovelist-dev/
batch_size: 256
cv_fold: 0
cv_folds: 10
db_path_eval:
  construct_from: smiles
  fp_map: './csi_fingerid_mod.tsv'
  path: /home/vo87poq/msnovelist/target/sirius6-2ec0d5a2-4d84-47d9-ac54-22ae2961d139.db
  pipeline_options:
    embed_X: false
    fingerprint_selected: fingerprint_degraded
  reload_smiles_pubchem: false
db_path_template:
  construct_from: smiles
  fp_map: './csi_fingerid_mod.tsv'
  path: './data/minimal-dataset/sirius6-minimal.db'
  pipeline_options:
    embed_X: false
  reload_smiles_pubchem: false
db_pubchem: './data/pubchem-dummy/pubchem_ref_dummy.db'
decoder_config:
  clip_invalid_counts: false
  tokenization: tokens_process
decoder_name: beam_search
epochs: 10
eval_counter: ''
eval_detail: false
eval_folder: './results/eval/'
eval_id: ''
eval_k: 128
eval_kk: 128
eval_n: 8
eval_n_total: 10
eval_steps: 128
eval_temperature: 1.0
eval_top_n: 1
evaluation_set: dataset
f1_cutoff: 0.5
fingerprinter_cache: './results/fingerprint_cache.db'
fingerprinter_path: './bin/'
fingerprinter_threads: 10
fp_map: './csi_fingerid.tsv'
fp_map_evaluation: './csi_fingerid_mod.tsv'
fp_overlay_method: none
fp_source: ''
hdf5_lock: 'FALSE'
java_memory: 2048
log_folder: './results/tensorboard/'
model_config:
  loss_weights:
    out_nhydrogen: 0.03
    out_smiles: 1
  use_auxiliary_counter: true
  use_fingerprint: true
  use_hydrogen_estimator: true
model_name: models.model_flex_20190401
model_tag: msnovelist-sirius6-weights
pipeline_encoder:
- fingerprint_selected
- mol_form
- n_hydrogen
pipeline_reference:
- smiles_canonical
- fingerprint_degraded
pipeline_x:
- fingerprint_selected
- mol_form
- tokens_X
pipeline_x_eval: []
pipeline_y:
- tokens_y
- n_hydrogen
preprocessing_preselect_limit: 1000000
preprocessing_workers_preselect: 10
preprocessing_workers_pubchem: 30
random_seed_global: ''
reinforcement_config:
  iterations_per_step: 1
  reinforcement_steps: 50
  reinforcement_steps_store:
  - 4
  - 9
  - 24
  - 49
  sigma: 50
  temperature: 2.0
reinforcement_eval_count: -1
reinforcement_eval_start: -1
rerank_sirius_results_n: 99999
sampler_config:
  final_round: true
  max_loop: 10
  replace_true: 0
#sampler_name: fp_sampling.cv_sampler_direct
sampler_name: ""
sirius_bin: './sirius/bin/sirius'
steps_per_epoch: -1
steps_per_epoch_validation: -1
tensorflow_trace: false
training_id: ''
training_set: train
training_verbose: 1
validation_set: validate
weights: w-25-0.067-0.073.hdf5
weights_folder: './data/weights/'